nav:
  - "*"
  - csc01_cpouta.md
  - lak01_ducklake.md
  - srk01_spark.md
  - srk02_delta.md
  - cdc01_mealie.md
  - str01_redpanda.md
  - orc01_airflow.md
  - orc02_dagster.md
  - kim01_kimball.md
  # todo: - cub01_olapkuutio.md
  - big01_raideliikenne.md
